=== tmasabari/AptTecReports/src/Data/Master/ReportParametersSchema1.json
{
    "$schema": "http://json-schema.org/draft-06/schema#",
    "$ref": "#/definitions/ReportParameters",
    "definitions": {
        "ReportParameters": {
            "type": "object",
            "additionalProperties": false,
            "properties": {
                "ReportTemplate": {
                    "type": "string"
                },
                "DataSource": {
                    "type": "string"
                },
                "Layout": {
                    "$ref": "#/definitions/Layout"
                },
                "HeadersHtml": {
                    "type": "string",
                    "format": "jodit"
                },
                "FootersHtml": {
                    "type": "string",
                    "format": "jodit"
                },
                "Headers": {
                    "$ref": "#/definitions/Headers"
                },
                "Footers": {
                    "$ref": "#/definitions/Footers"
                },
                "GridStyles": {
                    "$ref": "#/definitions/GridStyles"
                },
                "Columns": {
                    "type": "array",
                    "format": "table",
                    "items": {
                        "$ref": "#/definitions/Column"
                    }
                }
            },
            "required": [
                "Columns",
                "DataSource",
                "Footers",
                "GridStyles",
                "Headers",
                "Layout",
                "ReportTemplate"
            ],
            "title": "Report Parameters"
        },
        "Column": {
            "type": "object",
            "additionalProperties": false,
            "properties": {
                "field": {
                    "type": "string"
                },
                "displayName": {
                    "type": "string"
                },
                "columnSize": {
                    "type": "string"
                },
                "format": {
                    "type": "string"
                }
            },
            "required": [
                "displayName",
                "field"
            ],
            "title": "Column"
        },
        "Footers": {
            "type": "object",
            "additionalProperties": false,
            "properties": {
                "Report-Top-Margin": {
                    "type": "string",
                    "options": {
                        "hidden": true
                    },
                    "template": "{{input}}mm",
                    "watch": {
                        "input": "Report-Top-Margin-input"
                    }
                },
                "Page-Footer-Height": {
                    "type": "string",
                    "options": { "hidden": true },
                    "template": "{{input}}mm",
                    "watch": { "input": "Page-Footer-Height-input" }
                },
                "Report-Right-Margin": {
                    "type": "string",
                    "options": {
                        "hidden": true
                    },
                    "template": "{{input}}mm",
                    "watch": {
                        "input": "Report-Right-Margin-input"
                    }
                },
                "Report-Bottom-Margin": {
                    "type": "string",
                    "options": {
                        "hidden": true
                    },
                    "template": "{{input}}mm",
                    "watch": {
                        "input": "Report-Bottom-Margin-input"
                    }
                },
                "Report-Left-Margin": {
                    "type": "string",
                    "options": {
                        "hidden": true
                    },
                    "template": "{{input}}mm",
                    "watch": {
                        "input": "Report-Left-Margin-input"
                    }
                },
                "Page-Footer-Height": {
                    "type": "string",
                    "options": {
                        "hidden": true
                    },
                    "template": "{{input}}mm",
                    "watch": {
                        "input": "Page-Footer-Height-input"
                    }
                },
                "Page-Header-Height": {
                    "type": "string",
                    "options": {
                        "hidden": true
                    },
                    "template": "{{input}}mm",
                    "watch": {
                        "input": "Page-Header-Height-input"
                    }
                },
                "FooterLeftText": {
                    "type": "string"
                },
                "FooterRightText": {
                    "type": "string"
                },
                "FooterMiddleText1": {
                    "type": "string"
                },
                "FooterMiddleText2": {
                    "type": "string"
                },
                "FooterMiddleText3": {
                    "type": "string"
                },
                "FooterMiddleText4": {
                    "type": "string"
                },
                "FooterMiddleText5": {
                    "type": "string"
                },
                "FooterLeftStyle": {
                    "type": "string"
                },
                "FooterMiddleText1Style": {
                    "type": "string"
                },
                "FooterMiddleText2Style": {
                    "type": "string"
                },
                "FooterMiddleText3Style": {
                    "type": "string"
                },
                "FooterMiddleText4Style": {
                    "type": "string"
                },
                "FooterMiddleText5Style": {
                    "type": "string"
                },
                "FooterRightStyle": {
                    "type": "string"
                }
            },
            "required": [
                "FooterLeftStyle",
                "FooterLeftText",
                "FooterMiddleText1",
                "FooterMiddleText1Style",
                "FooterMiddleText2",
                "FooterMiddleText2Style",
                "FooterMiddleText3",
                "FooterMiddleText3Style",
                "FooterMiddleText4",
                "FooterMiddleText4Style",
                "FooterMiddleText5",
                "FooterMiddleText5Style",
                "FooterRightStyle",
                "FooterRightText"
            ],
            "title": "Footers"
        },
        "GridStyles": {
            "type": "object",
            "additionalProperties": false,
            "properties": {
                "gridHeaderStyle": {
                    "type": "string"
                },
                "gridStyle": {
                    "type": "string"
                },
                "Content-Table-Border": {
                    "type": "string"
                }
            },
            "required": [
                "Content-Table-Border",
                "gridHeaderStyle",
                "gridStyle"
            ],
            "title": "GridStyles"
        },
        "Headers": {
            "type": "object",
            "additionalProperties": false,
            "properties": {
                "HeaderLeftText": {
                    "type": "string"
                },
                "HeaderRightText": {
                    "type": "string"
                },
                "HeaderMiddleText1": {
                    "type": "string"
                },
                "HeaderMiddleText2": {
                    "type": "string"
                },
                "HeaderMiddleText3": {
                    "type": "string"
                },
                "HeaderMiddleText4": {
                    "type": "string"
                },
                "HeaderMiddleText5": {
                    "type": "string"
                },
                "HeaderLeftStyle": {
                    "type": "string"
                },
                "HeaderMiddleText1Style": {
                    "type": "string"
                },
                "HeaderMiddleText2Style": {
                    "type": "string"
                },
                "HeaderMiddleText3Style": {
                    "type": "string"
                },
                "HeaderMiddleText4Style": {
                    "type": "string"
                },
                "HeaderMiddleText5Style": {
                    "type": "string"
                },
                "HeaderRightStyle": {
                    "type": "string"
                }
            },
            "required": [
                "HeaderLeftStyle",
                "HeaderLeftText",
                "HeaderMiddleText1",
                "HeaderMiddleText1Style",
                "HeaderMiddleText2",
                "HeaderMiddleText2Style",
                "HeaderMiddleText3",
                "HeaderMiddleText3Style",
                "HeaderMiddleText4",
                "HeaderMiddleText4Style",
                "HeaderMiddleText5",
                "HeaderMiddleText5Style",
                "HeaderRightStyle",
                "HeaderRightText"
            ],
            "title": "Headers"
        },
        "Layout": {
            "type": "object",
            "additionalProperties": false,
            "properties": {
                "PaperSize": {
                    "type": "string"
                },
                "PaperLayout": {
                    "type": "string"
                },
                "Report-Top-Margin": {
                    "type": "string"
                },
                "Report-Right-Margin": {
                    "type": "string"
                },
                "Report-Bottom-Margin": {
                    "type": "string"
                },
                "Report-Left-Margin": {
                    "type": "string"
                },
                "Page-Header-Height": {
                    "type": "string"
                },
                "Page-Footer-Height": {
                    "type": "string"
                }
            },
            "required": [
                "Page-Footer-Height",
                "Page-Header-Height",
                "PaperLayout",
                "PaperSize",
                "Report-Bottom-Margin",
                "Report-Left-Margin",
                "Report-Right-Margin",
                "Report-Top-Margin"
            ],
            "title": "Layout"
        }
    }
}

=== tmasabari/AptTecReports/src/Data/Reports/jobQueueReport1.json
{
    "ReportTemplate": "paged.html",
    "DataSource": "../Data/Samples/jobs.json",
    "Layout": {
        "PaperSize": "legal",
        "PaperLayout": "landscape",
        "Report-Top-Margin": "6.5mm",
        "Report-Right-Margin": "6.5mm",
        "Report-Bottom-Margin": "6.5mm",
        "Report-Left-Margin": "6.5mm",
        "Page-Header-Height": "20mm",
        "Page-Footer-Height": "10mm"
    },
    "Headers": {
        "HeaderLeftText": "{OrgAddress1}<br/>{OrgAddress2}<br/>{OrgAddress3}",
        "HeaderRightText": "{@TodayDate('mm/dd/yyyy')@}",
        "HeaderMiddleText1": "{OrgTitle}",
        "HeaderMiddleText2": "{ReportTitle}",
        "HeaderMiddleText3": "{ReportSubTitle}",
        "HeaderMiddleText4": "",
        "HeaderMiddleText5": "",
        "HeaderLeftStyle": "font-size:11pt; font-weight: bold;",
        "HeaderMiddleText1Style": "font-size:11pt; font-weight: bold; margin-bottom:3mm;",
        "HeaderMiddleText2Style": "font-size:14pt; font-weight: bold; margin-bottom:2mm;",
        "HeaderMiddleText3Style": "font-size:12pt; font-weight: bold; margin-bottom:1mm;",
        "HeaderMiddleText4Style": "font-size:12pt; font-weight: bold; margin-bottom:1mm;",
        "HeaderMiddleText5Style": "font-size:12pt; font-weight: bold; margin-bottom:1mm;",
        "HeaderRightStyle": "font-size:11pt; font-weight: bold;"
    },
    "Footers": {
        "FooterLeftText": "left footer line 1<br/>left footer line 2",
        "FooterRightText": "right footer line 1<br/>",
        "FooterMiddleText1": "{Copyright}",
        "FooterMiddleText2": "",
        "FooterMiddleText3": "",
        "FooterMiddleText4": "",
        "FooterMiddleText5": "",
        "FooterLeftStyle": "font-size:11pt;",
        "FooterMiddleText1Style": "font-size:11pt; margin-bottom:1mm;",
        "FooterMiddleText2Style": "font-size:10pt; margin-bottom:1mm;",
        "FooterMiddleText3Style": "font-size:11pt; margin-bottom:1mm;",
        "FooterMiddleText4Style": "font-size:11pt; margin-bottom:1mm;",
        "FooterMiddleText5Style": "font-size:11pt; margin-bottom:1mm;",
        "FooterRightStyle": "font-size:11pt;"
    },
    "GridStyles": {
        "gridHeaderStyle": "font-weight: bold; ",
        "gridStyle": " margin-bottom: -1px;",
        "Content-Table-Border": "0.25mm"
    },
    "Columns": [
        {
            "field": "SubmitedDate",
            "displayName": "Submit Date",
            "columnSize": "10ch",
            "format": "USShortDateTime"
        },
        {
            "field": "SubmittedBy",
            "displayName": "Submitted By"
        },
        {
            "field": "PrintJobName",
            "columnSize": "13em",
            "displayName": "Job Name"
        },
        {
            "field": "Status",
            "columnSize": "5em",
            "displayName": "Status"
        },
        {
            "field": "FileName",
            "displayName": "File Name"
        },
        {
            "field": "FileSize",
            "columnSize": "10ch",
            "displayName": "Size"
        },
        {
            "field": "SubmitedDate",
            "displayName": "Created",
            "columnSize": "10ch",
            "format": "USShortDateTime"
        },
        {
            "field": "JobType",
            "displayName": "Job Type"
        }
    ]
}
