=== tmasabari/AptTecReports/src/Data/Schema/ReportParametersSchema.json
{
    "$schema": "http://json-schema.org/draft-06/schema#",
    "$ref": "#/definitions/ReportParameters",
    "definitions": {
        "ReportParameters": {
            "type": "object",
            "additionalProperties": false,
            "properties": {
                "ReportTemplate": {
                    "type": "string",
                    "options": { "hidden": true }
                },
                "DataSource": {
                    "type": "string" ,
                    "options": { "hidden": true }
                },
                "Layout": {
                    "$ref": "#/definitions/Layout"
                },
                "PageHeadersHtml": {
                    "type": "string",
                    "title": "Page Header",
                    "format": "jodit",
                    "options": {
                        "input_width": "100%"
                    }
                },
                "PageFootersHtml": {
                    "type": "string",
                    "title": "Page Footer",
                    "format": "jodit",
                    "options": {
                        "input_width": "100%"
                    }
                },
                "ReportHeadersHtml": {
                    "type": "string",
                    "title": "Report Header",
                    "format": "jodit",
                    "options": {
                        "input_width": "100%"
                    }
                },
                "ReportFootersHtml": {
                    "type": "string",
                    "title": "Report Footer",
                    "format": "jodit",
                    "options": {
                        "input_width": "100%"
                    }
                },
                "Content": {
                    "type": "array",
                    "items": {
                        "oneOf": [
                            {
                                "$ref": "#/definitions/Htmlcontent"
                            },
                            {
                                "$ref": "#/definitions/Table"
                            }
                        ]
                    },
                    "options": {
                        "disable_array_delete": true,
                        "disable_array_delete_all_rows": true,
                        "disable_array_add": true,
                        "disable_array_reorder": true
                    }

                }
            },
            "defaultProperties": [
                "Layout", "Content"
            ],
            "required": [
                "PageHeadersHtml",
                "PageFootersHtml",
                "DataSource",
                "Layout",
                "ReportTemplate"
            ],
            "title": "Report Parameters"
        },
        "Htmlcontent": {
            "type": "object",
            "additionalProperties": false,
            "properties": {
                "DataSource":{
                    "type": "string",
                    "options": { "hidden": true }
                },
                "ContentHtml": {
                    "type": "string",
                    "title": "HTML Content",
                    "format": "jodit",
                    "options": {
                        "input_width": "100%"
                    }
                }
            },
            "required": [
                "ContentHtml"
            ],
            "title": "Html Content"
        },
        "Table": {
            "type": "object",
            "additionalProperties": false,
            "properties": {
                "DataSource":{
                    "type": "string",
                    "options": { "hidden": true }
                },
                "TableContent": {
                    "type": "array",
                    "format": "table",
                    "items": {
                        "$ref": "#/definitions/Column"
                    },
                    "options": {
                        "disable_array_delete": true,
                        "disable_array_delete_all_rows": true,
                        "disable_array_add": true
                    }
                }
            },
            "required": [
                "TableContent"
            ],
            "title": "Table configuration"
        },
        
        "Column": {
            "type": "object",
            "additionalProperties": false,
            "properties": {
                "isPrint": {
                    "type": "boolean",
                    "format": "checkbox",
                    "title": "To Print"
                },
                "field": {
                    "type": "string",
                    "title": "Name"
                },
                "displayName": {
                    "type": "string",
                    "title": "Title"
                },
                "columnSize": {
                    "type": "string",
                    "title": "Width"
                },
                "format": {
                    "type": "string",
                    "title": "Format"
                }
            },
            "required": [
                "displayName",
                "field"
            ],
            "title": "Column"
        },
        "Layout": {
            "type": "object",
            "additionalProperties": false,
            "format": "grid-strict",
            "properties": {
                "PaperSize": {
                    "type": "string",
                    "title": "Paper size",
                    "enum": ["A3", "A4", "A5", "B4", "B5", "letter", "legal", "ledger"],
                    "options": {    "grid_columns": 4,
                                    "enum_titles": ["A3", "A4", "A5", "B4", "B5", "Letter", "Legal", "Ledger"] }
                },
                "PaperLayout": {
                    "type": "string",
                    "title": "Paper layout",
                    "enum": ["portrait", "landscape"],
                    "options": { "grid_columns": 4 , "grid_break": true,
                        "enum_titles": [
                            "Portrait",
                            "Landscape"
                        ] } 
                },
                "Report-Top-Margin": {
                    "type": "number",
                    "format": "number",
                    "title": "Top margin (mm)"
                },
                "Report-Right-Margin": {
                    "type": "number",
                    "format": "number",
                    "title": "Right margin (mm)"
                },
                "Report-Bottom-Margin": {
                    "type": "number",
                    "format": "number",
                    "title": "Bottom margin (mm)"
                },
                "Report-Left-Margin": {
                    "type": "number",
                    "format": "number",
                    "title": "Left margin (mm)"
                },
                "Page-Header-Height": {
                    "type": "number",
                    "format": "number",
                    "title": "Page header height (mm)"
                },
                "Page-Footer-Height": {
                    "type": "number",
                    "format": "number",
                    "title": "Page footer height (mm)"
                }
            },
            "required": [
                "PaperLayout",
                "PaperSize",
                "Report-Bottom-Margin",
                "Report-Left-Margin",
                "Report-Right-Margin",
                "Report-Top-Margin"
            ],
            "title": "Layout"
        }
    }
}

=== tmasabari/AptTecReports/src/Data/Templates/jobqueuereport.json
{
    "ReportTemplate": "paged.html",
    "DataSource": "{{sampleLocation}}/jobs.json",
    "PageHeadersHtml": "<table style=\"border-collapse:collapse;width: 100%;\"><tbody>\n<tr>\n\t<td style=\"width: 20%;text-align:left;\">{{OrgAddress1}}<br/>{{OrgAddress2}}<br/>{{OrgAddress3}}</td>\n\t<td style=\"width: 60%; text-align: center;\"><strong>{{OrgTitle}}<br/>{{ReportTitle}}<br/>{{ReportSubTitle}}</strong><br></td>\n\t<td style=\"width: 20%;text-align:right;\">{@TodayDate('mm/dd/yyyy')@}</td></tr></tbody></table>",
    "PageFootersHtml": "<table style=\"border-collapse:collapse;width: 100%;\"><tbody>\n<tr>\n\t<td style=\"width: 20%;text-align:left;\">left footer line 1<br/>left footer line 2</td>\n\t<td style=\"width: 60%; text-align: center;\"><strong>{{Copyright}}</strong><br></td>\n\t<td style=\"width: 20%;text-align:right;\">right footer line 1</td></tr></tbody></table>",
    "ReportHeadersHtml": "",
    "ReportFootersHtml": "",
    "Layout": {
        "PaperSize": "legal",
        "PaperLayout": "landscape",
        "Report-Top-Margin": 40,
        "Report-Right-Margin": 10,
        "Report-Bottom-Margin": 30,
        "Report-Left-Margin": 10
    },
    "Content": [
        {
            "ContentHtml": ""
        },
        {
            "DataSource": "jobsData",
            "TableContent": [
                {
                    "field": "SubmitedDate",
                    "displayName": "Submit Date",
                    "columnSize": "10ch",
                    "format": "USShortDateTime"
                },
                {
                    "field": "SubmittedBy",
                    "displayName": "Submitted By"
                },
                {
                    "field": "PrintJobName",
                    "columnSize": "13em",
                    "displayName": "Job Name"
                },
                {
                    "field": "Status",
                    "columnSize": "5em",
                    "displayName": "Status"
                },
                {
                    "field": "FileName",
                    "displayName": "File Name"
                },
                {
                    "field": "FileSize",
                    "columnSize": "10ch",
                    "displayName": "Size"
                },
                {
                    "field": "SubmitedDate",
                    "displayName": "Created",
                    "columnSize": "10ch",
                    "format": "USShortDateTime"
                },
                {
                    "field": "JobType",
                    "displayName": "Job Type"
                }
            ]
        }
    ]
}
