=== tmasabari/AptTecReports/src/Schema/ReportParametersSchema.json
{
    "$schema": "http://json-schema.org/draft-06/schema#",
    "$ref": "#/definitions/ReportParameters",
    "definitions": {
        "ReportParameters": {
            "type": "object",
            "additionalProperties": false,
            "properties": {
                "ReportTemplate": {
                    "type": "string",
                    "options": { "hidden": true }
                },
                "DataSource": {
                    "type": "string" ,
                    "options": { "hidden": true }
                },
                "Layout": {
                    "$ref": "#/definitions/Layout"
                },
                "PageHeadersHtml": {
                    "type": "string",
                    "title": "Page Header",
                    "format": "jodit",
                    "options": {
                        "input_width": "100%"
                    }
                },
                "PageFootersHtml": {
                    "type": "string",
                    "title": "Page Footer",
                    "format": "jodit",
                    "options": {
                        "input_width": "100%"
                    }
                },
                "ReportHeadersHtml": {
                    "type": "string",
                    "title": "Report Header",
                    "format": "jodit",
                    "options": {
                        "input_width": "100%"
                    }
                },
                "ReportFootersHtml": {
                    "type": "string",
                    "title": "Report Footer",
                    "format": "jodit",
                    "options": {
                        "input_width": "100%"
                    }
                },
                "Content": {
                    "type": "array",
                    "items": {
                        "oneOf": [
                            {
                                "$ref": "#/definitions/Htmlcontent"
                            },
                            {
                                "$ref": "#/definitions/Table"
                            }
                        ]
                    },
                    "options": {
                        "disable_array_delete": true,
                        "disable_array_delete_all_rows": true,
                        "disable_array_add": true,
                        "disable_array_reorder": true
                    }

                }
            },
            "defaultProperties": [
                "Layout", "Content"
            ],
            "required": [
                "PageHeadersHtml",
                "PageFootersHtml",
                "DataSource",
                "Layout",
                "ReportTemplate"
            ],
            "title": "Report Parameters"
        },
        "Htmlcontent": {
            "type": "object",
            "additionalProperties": false,
            "properties": {
                "DataSource":{
                    "type": "string",
                    "options": { "hidden": true }
                },
                "ContentHtml": {
                    "type": "string",
                    "title": "HTML Content",
                    "format": "jodit",
                    "options": {
                        "input_width": "100%"
                    }
                }
            },
            "required": [
                "ContentHtml"
            ],
            "title": "Html Content"
        },
        "Table": {
            "type": "object",
            "additionalProperties": false,
            "properties": {
                "DataSource":{
                    "type": "string",
                    "options": { "hidden": true }
                },
                "TableContent": {
                    "type": "array",
                    "format": "table",
                    "items": {
                        "$ref": "#/definitions/Column"
                    },
                    "options": {
                        "disable_array_delete": true,
                        "disable_array_delete_all_rows": true,
                        "disable_array_add": true
                    }
                }
            },
            "required": [
                "TableContent"
            ],
            "title": "Table configuration"
        },
        
        "Column": {
            "type": "object",
            "additionalProperties": false,
            "properties": {
                "isPrint": {
                    "type": "boolean",
                    "format": "checkbox",
                    "title": "To Print"
                },
                "field": {
                    "type": "string",
                    "title": "Name",
                    "options": { "hidden": true }
                },
                "displayName": {
                    "type": "string",
                    "title": "Title"
                },
                "columnSize": {
                    "type": "string",
                    "title": "Width",
                    "options": { "input_width": "10ch" }
                },
                "format": {
                    "type": "string",
                    "title": "Format"
                },
                "maxLength": {
                    "type": "number",
                    "format": "number",
                    "title": "First N Chars",
                    "options": { "input_width": "10ch" }
                },
                "TitleStyle": {
                    "type": "string",
                    "title": "Title Style"
                },
                "ContentStyle": {
                    "type": "string",
                    "title": "Content Style"
                },
                "PageCount": {
                    "type": "boolean",
                    "format": "checkbox",
                    "title": "Content Style"
                },
                "TotalCount": {
                    "type": "boolean",
                    "format": "checkbox",
                    "title": "Content Style"
                }
            },
            "required": [
                "displayName",
                "field"
            ],
            "title": "Column"
        },
        "Layout": {
            "type": "object",
            "additionalProperties": false,
            "format": "grid-strict",
            "properties": {
                "PaperSize": {
                    "type": "string",
                    "title": "Paper size",
                    "enum": ["A3", "A4", "A5", "B4", "B5", "letter", "legal", "ledger"],
                    "options": {    "input_width": "20ch",
                                    "enum_titles": ["A3", "A4", "A5", "B4", "B5", "Letter", "Legal", "Ledger"] }
                },
                "PaperLayout": {
                    "type": "string",
                    "title": "Paper layout",
                    "enum": ["portrait", "landscape"],
                    "options": { "input_width": "20ch", "grid_break": true,
                        "enum_titles": [
                            "Portrait",
                            "Landscape"
                        ] } 
                },
                "Report-Top-Margin": {
                    "type": "number",
                    "format": "number",
                    "title": "Top margin (mm)"
                },
                "Report-Right-Margin": {
                    "type": "number",
                    "format": "number",
                    "title": "Right margin (mm)"
                },
                "Report-Bottom-Margin": {
                    "type": "number",
                    "format": "number",
                    "title": "Bottom margin (mm)"
                },
                "Report-Left-Margin": {
                    "type": "number",
                    "format": "number",
                    "title": "Left margin (mm)"
                },
                "Page-Header-Height": {
                    "type": "number",
                    "format": "number",
                    "title": "Page header height (mm)"
                },
                "Page-Footer-Height": {
                    "type": "number",
                    "format": "number",
                    "title": "Page footer height (mm)",
                    "options": { "grid_break": true }
                },
                "CustomStyle": {
                    "type": "string",
                    "title": "Custom content styles",
                    "format": "textarea",
                    "options": {"input_width": "100%", "expand_height":"true"}
                }
            },
            "required": [
                "PaperLayout",
                "PaperSize",
                "Report-Bottom-Margin",
                "Report-Left-Margin",
                "Report-Right-Margin",
                "Report-Top-Margin",
                "Page-Header-Height",
                "Page-Footer-Height",
                "CustomStyle"
            ],
            "title": "Layout"
        }
    }
}

=== tmasabari/AptTecReports/test/Data/Templates/countsReport.json
{
    "Layout": {
        "PaperSize": "legal",
        "PaperLayout": "landscape",
        "Report-Top-Margin": 5,
        "Report-Right-Margin": 5,
        "Report-Bottom-Margin": 5,
        "Report-Left-Margin": 5,
        "Page-Header-Height": 30,
        "Page-Footer-Height": 5,
        "CustomStyle": ".content .dataTable td { border: 0px; }\n.content .dataTable th  { border-width: 1px 0px; }\n .content .dataTable { border-width: 0px 0px 1px 0px;}"
    },
    "Content": [
        {
            "TableContent": [
                {
                    "isPrint": true,
                    "field": "Description",
                    "displayName": "Description",
                    "columnSize": "15ch",
                    "format": "",
                    "maxLength": 0,
                    "TitleStyle": "text-align:left;",
                    "ContentStyle": "text-align:left;"
                },
                {
                    "isPrint": true,
                    "field": "ReceiptsCount",
                    "displayName": "Receipts",
                    "columnSize": "5ch",
                    "format": "",
                    "maxLength": 0,
                    "TitleStyle": "text-align:right",
                    "ContentStyle": "text-align:right; ",
                    "TotalCount": true
                },
                {
                    "isPrint": true,
                    "field": "ReceiptsPercentage",
                    "displayName": "%",
                    "columnSize": "3ch",
                    "format": "",
                    "maxLength": 0,
                    "TitleStyle": "text-align:right",
                    "ContentStyle": "text-align:right; ",
                    "TotalCount": true
                },
                {
                    "isPrint": true,
                    "field": "ItemsCount",
                    "displayName": "Items Count",
                    "columnSize": "5ch",
                    "format": "",
                    "maxLength": 0,
                    "TitleStyle": "text-align:right",
                    "ContentStyle": "text-align:right; ",
                    "TotalCount": true
                },
                {
                    "isPrint": true,
                    "field": "ItemsPercentage",
                    "displayName": "%",
                    "columnSize": "3ch",
                    "format": "",
                    "maxLength": 0,
                    "TitleStyle": "text-align:right",
                    "ContentStyle": "text-align:right; ",
                    "TotalCount": true
                },
                {
                    "isPrint": true,
                    "field": "CorrectionCount",
                    "displayName": "Correction",
                    "columnSize": "5ch",
                    "format": "",
                    "maxLength": 0,
                    "TitleStyle": "text-align:right",
                    "ContentStyle": "text-align:right; ",
                    "TotalCount": true
                },
                {
                    "isPrint": true,
                    "field": "CorrectionPercentage",
                    "displayName": "%",
                    "columnSize": "3ch",
                    "format": "",
                    "maxLength": 0,
                    "TitleStyle": "text-align:right",
                    "ContentStyle": "text-align:right; ",
                    "TotalCount": true
                },
                {
                    "isPrint": true,
                    "field": "BillsCount",
                    "displayName": "Bills Count",
                    "columnSize": "5ch",
                    "format": "",
                    "maxLength": 0,
                    "TitleStyle": "text-align:right",
                    "ContentStyle": "text-align:right; ",
                    "TotalCount": true
                },
                {
                    "isPrint": true,
                    "field": "BillsPercentage",
                    "displayName": "%",
                    "columnSize": "3ch",
                    "format": "",
                    "maxLength": 0,
                    "TitleStyle": "text-align:right",
                    "ContentStyle": "text-align:right; ",
                    "TotalCount": true
                }
            ]
        }
    ],
    "ReportTemplate": "paged.html",
    "DataSource": "",
    "PageHeadersHtml": "<table style=\"border-collapse:collapse;width: 100%;\">\n    <tbody>\n        <tr>\n            <td style=\"width: 20%;text-align:left;\">{{OrgAddress1}}<br>{{OrgAddress2}}<br>{{OrgAddress3}}</td>\n            <td style=\"width: 60%; text-align: center;\">{{ClientTitle}}<br><strong style=\"font-family: &quot;times new roman&quot;, times, serif; font-size: 24px;\">Productivity Report</strong><br>Report Date <strong>{{StartDate}} - {{EndDate}}</strong></td>\n            <td style=\"width: 20%;text-align:right;\">Page{{PI}} of {{PC}}<br>{{CurrentDateTime}}</td>\n        </tr>\n    </tbody>\n</table>",
    "PageFootersHtml": "",
    "ReportFootersHtml": "",
    "ReportHeadersHtml": ""
}

=== tmasabari/AptTecReports/src/Data/Templates/letter.json
{
    "ReportTemplate": "paged.html",
    "DataSource": "",
    "PageHeadersHtml": "<table style=\"border-collapse:collapse;width: 100%;\"><tbody>\n<tr>\n\t<td style=\"width: 20%;text-align:left;\">{{OrgAddress1}}<br/>{{OrgAddress2}}<br/>{{OrgAddress3}}</td>\n\t<td style=\"width: 60%; text-align: center;\"><strong>{{OrgTitle}}<br/>{{ReportTitle}}<br/>{{ReportSubTitle}}</strong><br></td>\n\t<td style=\"width: 20%;text-align:right;\">{{CurrentDateTime}}</td></tr></tbody></table>",
    "PageFootersHtml": "<table style=\"border-collapse:collapse;width: 100%;\"><tbody>\n<tr>\n\t<td style=\"width: 20%;text-align:left;\">left footer line 1<br/>left footer line 2</td>\n\t<td style=\"width: 60%; text-align: center;\"><strong>{{Copyright}}</strong><br></td>\n\t<td style=\"width: 20%;text-align:right;\">right footer line 1</td></tr></tbody></table>",
    "ReportHeadersHtml":"",
    "ReportFootersHtml": "",
    "Content": [
        {"ContentHtml":"<p><br></p><p><br></p><table style=\"border-collapse: collapse; width: 852px; height: 278px;\">\n    <tbody>\n        <tr>\n            <td style=\"width: 21.4789%;\"><strong>Document #</strong><br></td>\n            <td style=\"width: 78.4038%;\">123123</td>\n        </tr>\n        <tr>\n            <td><strong>Received From</strong><br></td>\n            <td>{{ClientName}}<br></td>\n        </tr>\n        <tr>\n            <td><br></td>\n            <td><br></td>\n        </tr>\n        <tr>\n            <td><br></td>\n            <td>{{ClientAddress1}}</td>\n        </tr>\n        <tr>\n            <td><br></td>\n            <td>{{ClientAddress2}} <br></td>\n        </tr>\n        <tr>\n            <td><br></td>\n            <td>{{ClientAddress3}}<br></td>\n        </tr>\n        <tr>\n            <td><br></td>\n            <td>{{ClientState}} {{ClientPin}}</td>\n        </tr>\n    </tbody>\n</table><br><br><br><br><br><table style=\"border:none;width: 100%;\"><tbody>\n<tr>\n\t<td style=\"width: 12.2521%;\"><br></td>\n\t<td style=\"width: 20.6091%;\"><br></td>\n\t\n\t\n\t\n\t<td style=\"width: 43.7844%; text-align: center;\">{{OfficialName}}</td></tr>\n<tr>\n\t<td><strong>On</strong></td>\n\t<td>{{DocumentDate}}<br></td>\n\t\n\t\n\t\n\t<td style=\"text-align: center;\"><br></td></tr>\n<tr>\n\t<td><strong>At</strong></td>\n\t<td>{{DocumentTime}}</td>\n\t\n\t\n\t\n\t<td style=\"text-align: center;\">I certify that this is a true copy of the attached document.<br></td></tr>\n<tr>\n\t<td><strong>Cover Sheet</strong></td>\n\t<td>1</td>\n\t\n\t\n\t\n\t<td><br></td></tr>\n<tr>\n\t<td><strong>Total Pages</strong></td>\n\t<td>10</td>\n\t\n\t\n\t\n\t<td style=\" text-align: center;\">{{OfficialTitle}}</td></tr></tbody></table><p><br></p><p><br></p><p><br></p>"}
    ], 
    "Layout": {
        "PaperSize": "A4",
        "PaperLayout": "portrait",
        "Report-Top-Margin": 10,
        "Report-Right-Margin": 10,
        "Report-Bottom-Margin": 10,
        "Report-Left-Margin": 10,
        "Page-Header-Height": 30,
        "Page-Footer-Height": 20,
        "CustomStyle": ""
    }
}

=== tmasabari/AptTecReports/src/Data/Templates/dailyTotals.json
{
    "ReportTemplate": "paged.html",
    "DataSource": "",
    "PageHeadersHtml": "<table style=\"border-collapse:collapse;width: 100%;\"><tbody>\n<tr>\n\t<td style=\"width: 30%;text-align:left;\">{{OrgAddress1}}<br/>{{OrgAddress2}}<br/>{{OrgAddress3}}</td>\n\t<td style=\"width: 40%; text-align: center;\"><strong>{{ClientTitle}}<br/>Daily Totals for the period between {{ReportStartDate}} and {{ReportEndDate}}</strong><br></td>\n\t<td style=\"width: 30%;text-align:right;\">{{CurrentDateTime}}<br/>Page{{PI}} of {{PC}}</td></tr></tbody></table>",
    "PageFootersHtml": "",
    "ReportFootersHtml": "",
    "ReportHeadersHtml": "",
    "Layout": {
        "PaperSize": "A4",
        "PaperLayout": "portrait",
        "Report-Top-Margin": 10,
        "Report-Right-Margin": 10,
        "Report-Bottom-Margin": 10,
        "Report-Left-Margin": 10,
        "Page-Header-Height": 30,
        "Page-Footer-Height": 20,
        "CustomStyle": ""
    },
    "Content": [
        {
            "TableContent": [
                {
                    "field": "orderDate",
                    "displayName": "Order Date",
                    "columnSize": "10ch",
                    "format": "",
                    "isPrint": true,
                    "ContentStyle": "text-align:center;"
                },
                {
                    "field": "regularCount",
                    "columnSize": "5ch",
                    "displayName": "Regular Count",
                    "isPrint": true,
                    "format":"decimal",
                    "ContentStyle": "text-align:right;"
                },
                {
                    "field": "regularTotal",
                    "columnSize": "5ch",
                    "displayName": "Regular Fees",
                    "isPrint": true,
                    "format": "currency",
                    "ContentStyle": "text-align:right;"
                },
                {
                    "field": "subscriptionCount",
                    "columnSize": "5ch",
                    "displayName": "Subscription Count",
                    "isPrint": true,
                    "format": "decimal",
                    "ContentStyle": "text-align:right;"
                },
                {
                    "field": "subscriptionTotal",
                    "columnSize": "5ch",
                    "displayName": "Subscription Fees",
                    "isPrint": true,
                    "format": "currency",
                    "ContentStyle": "text-align:right;"
                },
                {
                    "field": "othersCount",
                    "columnSize": "5ch",
                    "displayName": "Transactions Count",
                    "isPrint": true,
                    "format": "decimal",
                    "ContentStyle": "text-align:right;"
                },
                {
                    "field": "othersTotal",
                    "columnSize": "5ch",
                    "displayName": "Transactions Fees",
                    "isPrint": true,
                    "format": "currency",
                    "ContentStyle": "text-align:right;"
                },
                {
                    "field": "dailyTotal",
                    "columnSize": "5ch",
                    "displayName": "Daily Total",
                    "isPrint": true,
                    "format": "currency",
                    "TitleStyle": "",
                    "ContentStyle": "text-align:right;"
                }
            ]
        }
    ]
}

=== tmasabari/AptTecReports/test/Data/Templates/jobqueuereport.json
{
    "Layout": {
        "PaperSize": "A4",
        "PaperLayout": "portrait",
        "Report-Top-Margin": 10,
        "Report-Right-Margin": 10,
        "Report-Bottom-Margin": 7,
        "Report-Left-Margin": 10,
        "Page-Header-Height": 30,
        "Page-Footer-Height": 20,
        "CustomStyle": ""
    },
    "Content": [
        {
            "DataSource": "jobsData",
            "TableContent": [
                {
                    "isPrint": true,
                    "field": "FileName",
                    "displayName": "File Name",
                    "columnSize": "",
                    "format": "",
                    "maxLength": 0,
                    "TitleStyle": "",
                    "ContentStyle": "",
                    "TotalCount": false
                },
                {
                    "isPrint": true,
                    "field": "SubmitedDate",
                    "displayName": "Submit Date",
                    "columnSize": "10ch",
                    "format": "shortdatetime",
                    "maxLength": 0,
                    "TitleStyle": "",
                    "ContentStyle": "",
                    "TotalCount": false
                },
                {
                    "isPrint": true,
                    "field": "SubmittedBy",
                    "displayName": "Submitted By",
                    "columnSize": "10ch",
                    "format": "",
                    "maxLength": 0,
                    "TitleStyle": "",
                    "ContentStyle": "",
                    "TotalCount": false
                },
                {
                    "isPrint": true,
                    "field": "PrintJobName",
                    "displayName": "Job Name",
                    "columnSize": "10ch",
                    "format": "",
                    "maxLength": 0,
                    "TitleStyle": "",
                    "ContentStyle": "",
                    "TotalCount": false
                },
                {
                    "isPrint": true,
                    "field": "Status",
                    "displayName": "Status",
                    "columnSize": "5em",
                    "format": "",
                    "maxLength": 0,
                    "TitleStyle": "",
                    "ContentStyle": "",
                    "TotalCount": false
                },
                {
                    "isPrint": true,
                    "field": "FileSize",
                    "displayName": "Size",
                    "columnSize": "10ch",
                    "format": "",
                    "maxLength": 0,
                    "TitleStyle": "",
                    "ContentStyle": "",
                    "TotalCount": false
                },
                {
                    "isPrint": true,
                    "field": "SubmitedDate",
                    "displayName": "Created",
                    "columnSize": "10ch",
                    "format": "shortdatetime",
                    "maxLength": 0,
                    "TitleStyle": "",
                    "ContentStyle": "",
                    "TotalCount": false
                },
                {
                    "isPrint": true,
                    "field": "JobType",
                    "displayName": "Job Type",
                    "columnSize": "10ch",
                    "format": "",
                    "maxLength": 0,
                    "TitleStyle": "",
                    "ContentStyle": "",
                    "TotalCount": false
                }
            ]
        },
        {
            "ContentHtml": "<br>Section 1:  Extra formatted HTML content can be placed here"
        },
        {
            "ContentHtml": "<br><br>Section 2:  Extra formatted HTML content can be placed here"
        }
    ],
    "ReportTemplate": "paged.html",
    "DataSource": "/test/Data/Samples/jobs.json",
    "PageHeadersHtml": "<table style=\"border-collapse:collapse;width: 100%;\"><tbody>\n<tr>\n\t<td style=\"width: 20%;text-align:left;\">{{OrgAddress1}}<br>{{OrgAddress2}}<br>{{OrgAddress3}}</td>\n\t<td style=\"width: 60%; text-align: center;\"><strong>{{OrgTitle}}<br>{{ReportTitle}}<br>Analysis for the period between {{ReportStartDate}} and {{ReportEndDate}}</strong><br></td>\n\t<td style=\"width: 20%;text-align:right;\">{{CurrentDateTime}}<br>Page{{PI}} of {{PC}}</td></tr></tbody></table>",
    "PageFootersHtml": "<table style=\"border-collapse:collapse;width: 100%;\"><tbody>\n<tr>\n\t<td style=\"width: 20%;text-align:left;\">left footer line 1<br>left footer line 2</td>\n\t<td style=\"width: 60%; text-align: center;\"><strong>{{Copyright}}</strong><br></td>\n\t<td style=\"width: 20%;text-align:right;\">right footer line 1</td></tr></tbody></table>",
    "ReportFootersHtml": "<table style=\"border-collapse:collapse;width: 100%;\"><tbody>\n<tr>\n\t<td style=\"width: 27.719%; text-align: left;\"><br></td>\n\t<td style=\"width: 48.4119%; text-align: center;\"><br>Report footer- This will appear only once per report at the end<br></td>\n\t<td style=\"width: 23.7729%; text-align: right;\"><br></td></tr></tbody></table>",
    "ReportHeadersHtml": "<table style=\"border-collapse:collapse;width: 100%;\"><tbody>\n<tr>\n\t<td style=\"width: 27.719%; text-align: left;\"><br></td>\n\t<td style=\"width: 48.4119%; text-align: center;\">Report Header- This will appear only once per report on the top<br></td>\n\t<td style=\"width: 23.7729%; text-align: right;\"><br></td></tr></tbody></table>"
}
